---
  - name: Print env variable
    shell: echo $PATH
    register: print_result

  - name: print message
    debug:
      msg: "{{ print_result.stdout_lines }}"

  - name: create folder
    shell: mkdir -p ~/foundyou
