version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo hello "
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say World"
          command: "echo world!"
  useful_info:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Useful Global build-in vars"
          command: |
            echo My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>.
            echo <<pipeline.project.type>> - <<pipeline.project.git_url>>
            echo <<Author>>
workflows:
  say-hello-workflow:
    jobs:
      - print_hello
      - useful_info
      - print_world:
          requires:
            - print_hello
