version: 2.1
commands: # similar to function (reusable)
  print_pipeline_id:
    description: print current pipeline.id
    parameters:
      additional_print:
        type: string
        default: "Hello World!"
    steps:
      - run: echo <<pipeline.id>>
      - run: echo $CIRCLE_WORKFLOW_ID
      - run: echo <<parameters.additional_print>>

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            pwd
            echo "hello world" > output.txt
            mkdir sandbox
            echo "Secret" > ./sandbox/secret.txt
            ls -la
      - persist_to_workspace:
          root: .
          paths:
            - output*
      - persist_to_workspace:
          root: ./sandbox
          paths:
            - "*"

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - attach_workspace:
          at: ./sandbox
      - run:
          command: |
            ls -la
            cat output.txt
            cat ./sandbox/secret.txt

  useful_info:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - print_pipeline_id:
          additional_print: "BaoTruong"
      - run:
          name: "Useful Global build-in vars"
          command: |
            whoami
            ls -la
            sudo -l
            echo My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>.
            echo <<pipeline.project.type>> - <<pipeline.project.git_url>>
            echo ${Author}
workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
      - useful_info
      - print_output_file:
          requires:
            - save_hello_world_output
